#' A/B Testing Data
#'
#' Results of an A/B test conducted for an online shopping site.
#'
#' @docType data
#' @format A data frame with 5,000 rows and 11 variables:
#' \describe{
#'   \item{buy}{Integer. Binary outcome indicator (\code{0 = did not buy}, \code{1 = bought}).}
#'   \item{rev}{Numeric. Revenue generated by the customer after the experiment.}
#'   \item{coupon}{Integer. Treatment indicator (\code{0 = no coupon}, \code{1 = received coupon}).}
#'   \item{channel}{Factor or character. Acquisition channel (\code{Google}, \code{Facebook},
#'     \code{Instagram}, \code{Other}).}
#'   \item{prevnum}{Integer. Number of previous purchases prior to the experiment.}
#'   \item{prevrev}{Numeric. Total revenue from previous purchases.}
#'   \item{recency}{Numeric. Weeks since last visit prior to the experiment.}
#'   \item{prevtime}{Numeric. Minutes spent browsing the site during the previous visit.}
#'   \item{abandon}{Integer. Previous-visit cart abandonment (\code{0 = no}, \code{1 = yes}).}
#'   \item{minority}{Integer. Binary indicator (\code{0 = no}, \code{1 = yes}).}
#'   \item{female}{Integer. Binary indicator (\code{0 = no}, \code{1 = yes}).}
#' }
#' @source Unknown.
"ab.data"
